// Generated by gencpp from file manipulation_msgs/GraspPlanningErrorCode.msg
// DO NOT EDIT!


#ifndef MANIPULATION_MSGS_MESSAGE_GRASPPLANNINGERRORCODE_H
#define MANIPULATION_MSGS_MESSAGE_GRASPPLANNINGERRORCODE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace manipulation_msgs
{
template <class ContainerAllocator>
struct GraspPlanningErrorCode_
{
  typedef GraspPlanningErrorCode_<ContainerAllocator> Type;

  GraspPlanningErrorCode_()
    : value(0)  {
    }
  GraspPlanningErrorCode_(const ContainerAllocator& _alloc)
    : value(0)  {
  (void)_alloc;
    }



   typedef int32_t _value_type;
  _value_type value;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(SUCCESS)
  #undef SUCCESS
#endif
#if defined(_WIN32) && defined(TF_ERROR)
  #undef TF_ERROR
#endif
#if defined(_WIN32) && defined(OTHER_ERROR)
  #undef OTHER_ERROR
#endif

  enum {
    SUCCESS = 0,
    TF_ERROR = 1,
    OTHER_ERROR = 2,
  };


  typedef boost::shared_ptr< ::manipulation_msgs::GraspPlanningErrorCode_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::manipulation_msgs::GraspPlanningErrorCode_<ContainerAllocator> const> ConstPtr;

}; // struct GraspPlanningErrorCode_

typedef ::manipulation_msgs::GraspPlanningErrorCode_<std::allocator<void> > GraspPlanningErrorCode;

typedef boost::shared_ptr< ::manipulation_msgs::GraspPlanningErrorCode > GraspPlanningErrorCodePtr;
typedef boost::shared_ptr< ::manipulation_msgs::GraspPlanningErrorCode const> GraspPlanningErrorCodeConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::manipulation_msgs::GraspPlanningErrorCode_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::manipulation_msgs::GraspPlanningErrorCode_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::manipulation_msgs::GraspPlanningErrorCode_<ContainerAllocator1> & lhs, const ::manipulation_msgs::GraspPlanningErrorCode_<ContainerAllocator2> & rhs)
{
  return lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::manipulation_msgs::GraspPlanningErrorCode_<ContainerAllocator1> & lhs, const ::manipulation_msgs::GraspPlanningErrorCode_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace manipulation_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::manipulation_msgs::GraspPlanningErrorCode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::manipulation_msgs::GraspPlanningErrorCode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manipulation_msgs::GraspPlanningErrorCode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manipulation_msgs::GraspPlanningErrorCode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manipulation_msgs::GraspPlanningErrorCode_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manipulation_msgs::GraspPlanningErrorCode_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::manipulation_msgs::GraspPlanningErrorCode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d0cbf262cc3d8075a46b994eef1bdb2a";
  }

  static const char* value(const ::manipulation_msgs::GraspPlanningErrorCode_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd0cbf262cc3d8075ULL;
  static const uint64_t static_value2 = 0xa46b994eef1bdb2aULL;
};

template<class ContainerAllocator>
struct DataType< ::manipulation_msgs::GraspPlanningErrorCode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "manipulation_msgs/GraspPlanningErrorCode";
  }

  static const char* value(const ::manipulation_msgs::GraspPlanningErrorCode_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::manipulation_msgs::GraspPlanningErrorCode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Error codes for grasp and place planning\n"
"\n"
"# plan completed as expected\n"
"int32 SUCCESS = 0\n"
"\n"
"# tf error encountered while transforming\n"
"int32 TF_ERROR = 1 \n"
"\n"
"# some other error\n"
"int32 OTHER_ERROR = 2\n"
"\n"
"# the actual value of this error code\n"
"int32 value\n"
;
  }

  static const char* value(const ::manipulation_msgs::GraspPlanningErrorCode_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::manipulation_msgs::GraspPlanningErrorCode_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GraspPlanningErrorCode_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::manipulation_msgs::GraspPlanningErrorCode_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::manipulation_msgs::GraspPlanningErrorCode_<ContainerAllocator>& v)
  {
    s << indent << "value: ";
    Printer<int32_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MANIPULATION_MSGS_MESSAGE_GRASPPLANNINGERRORCODE_H
