// Generated by gencpp from file manipulation_msgs/GraspPlanning.msg
// DO NOT EDIT!


#ifndef MANIPULATION_MSGS_MESSAGE_GRASPPLANNING_H
#define MANIPULATION_MSGS_MESSAGE_GRASPPLANNING_H

#include <ros/service_traits.h>


#include <manipulation_msgs/GraspPlanningRequest.h>
#include <manipulation_msgs/GraspPlanningResponse.h>


namespace manipulation_msgs
{

struct GraspPlanning
{

typedef GraspPlanningRequest Request;
typedef GraspPlanningResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GraspPlanning
} // namespace manipulation_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::manipulation_msgs::GraspPlanning > {
  static const char* value()
  {
    return "4c2871ee002c11bedb77ea487288e711";
  }

  static const char* value(const ::manipulation_msgs::GraspPlanning&) { return value(); }
};

template<>
struct DataType< ::manipulation_msgs::GraspPlanning > {
  static const char* value()
  {
    return "manipulation_msgs/GraspPlanning";
  }

  static const char* value(const ::manipulation_msgs::GraspPlanning&) { return value(); }
};


// service_traits::MD5Sum< ::manipulation_msgs::GraspPlanningRequest> should match
// service_traits::MD5Sum< ::manipulation_msgs::GraspPlanning >
template<>
struct MD5Sum< ::manipulation_msgs::GraspPlanningRequest>
{
  static const char* value()
  {
    return MD5Sum< ::manipulation_msgs::GraspPlanning >::value();
  }
  static const char* value(const ::manipulation_msgs::GraspPlanningRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::manipulation_msgs::GraspPlanningRequest> should match
// service_traits::DataType< ::manipulation_msgs::GraspPlanning >
template<>
struct DataType< ::manipulation_msgs::GraspPlanningRequest>
{
  static const char* value()
  {
    return DataType< ::manipulation_msgs::GraspPlanning >::value();
  }
  static const char* value(const ::manipulation_msgs::GraspPlanningRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::manipulation_msgs::GraspPlanningResponse> should match
// service_traits::MD5Sum< ::manipulation_msgs::GraspPlanning >
template<>
struct MD5Sum< ::manipulation_msgs::GraspPlanningResponse>
{
  static const char* value()
  {
    return MD5Sum< ::manipulation_msgs::GraspPlanning >::value();
  }
  static const char* value(const ::manipulation_msgs::GraspPlanningResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::manipulation_msgs::GraspPlanningResponse> should match
// service_traits::DataType< ::manipulation_msgs::GraspPlanning >
template<>
struct DataType< ::manipulation_msgs::GraspPlanningResponse>
{
  static const char* value()
  {
    return DataType< ::manipulation_msgs::GraspPlanning >::value();
  }
  static const char* value(const ::manipulation_msgs::GraspPlanningResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MANIPULATION_MSGS_MESSAGE_GRASPPLANNING_H
