(cl:in-package manipulation_msgs-msg)
(cl:export '(ARM_NAME-VAL
          ARM_NAME
          TARGET-VAL
          TARGET
          COLLISION_OBJECT_NAME-VAL
          COLLISION_OBJECT_NAME
          COLLISION_SUPPORT_SURFACE_NAME-VAL
          COLLISION_SUPPORT_SURFACE_NAME
          GRASPS_TO_EVALUATE-VAL
          GRASPS_TO_EVALUATE
          MOVABLE_OBSTACLES-VAL
          MOVABLE_OBSTACLES
))