// Generated by gencpp from file household_objects_database_msgs/SaveScan.msg
// DO NOT EDIT!


#ifndef HOUSEHOLD_OBJECTS_DATABASE_MSGS_MESSAGE_SAVESCAN_H
#define HOUSEHOLD_OBJECTS_DATABASE_MSGS_MESSAGE_SAVESCAN_H

#include <ros/service_traits.h>


#include <household_objects_database_msgs/SaveScanRequest.h>
#include <household_objects_database_msgs/SaveScanResponse.h>


namespace household_objects_database_msgs
{

struct SaveScan
{

typedef SaveScanRequest Request;
typedef SaveScanResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SaveScan
} // namespace household_objects_database_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::household_objects_database_msgs::SaveScan > {
  static const char* value()
  {
    return "855c7b6f2658d8a9de03dd9a5f7b1f1e";
  }

  static const char* value(const ::household_objects_database_msgs::SaveScan&) { return value(); }
};

template<>
struct DataType< ::household_objects_database_msgs::SaveScan > {
  static const char* value()
  {
    return "household_objects_database_msgs/SaveScan";
  }

  static const char* value(const ::household_objects_database_msgs::SaveScan&) { return value(); }
};


// service_traits::MD5Sum< ::household_objects_database_msgs::SaveScanRequest> should match
// service_traits::MD5Sum< ::household_objects_database_msgs::SaveScan >
template<>
struct MD5Sum< ::household_objects_database_msgs::SaveScanRequest>
{
  static const char* value()
  {
    return MD5Sum< ::household_objects_database_msgs::SaveScan >::value();
  }
  static const char* value(const ::household_objects_database_msgs::SaveScanRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::household_objects_database_msgs::SaveScanRequest> should match
// service_traits::DataType< ::household_objects_database_msgs::SaveScan >
template<>
struct DataType< ::household_objects_database_msgs::SaveScanRequest>
{
  static const char* value()
  {
    return DataType< ::household_objects_database_msgs::SaveScan >::value();
  }
  static const char* value(const ::household_objects_database_msgs::SaveScanRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::household_objects_database_msgs::SaveScanResponse> should match
// service_traits::MD5Sum< ::household_objects_database_msgs::SaveScan >
template<>
struct MD5Sum< ::household_objects_database_msgs::SaveScanResponse>
{
  static const char* value()
  {
    return MD5Sum< ::household_objects_database_msgs::SaveScan >::value();
  }
  static const char* value(const ::household_objects_database_msgs::SaveScanResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::household_objects_database_msgs::SaveScanResponse> should match
// service_traits::DataType< ::household_objects_database_msgs::SaveScan >
template<>
struct DataType< ::household_objects_database_msgs::SaveScanResponse>
{
  static const char* value()
  {
    return DataType< ::household_objects_database_msgs::SaveScan >::value();
  }
  static const char* value(const ::household_objects_database_msgs::SaveScanResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HOUSEHOLD_OBJECTS_DATABASE_MSGS_MESSAGE_SAVESCAN_H
